# Render.yaml - Configuração para implantação no Render

services:
  # Serviço para o backend
  - type: web
    name: instagram-analyzer-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: CORS_ORIGIN
        value: https://instagram-analyzer-frontend.vercel.app
      - key: REPORTS_DIR
        value: ./reports
    disk:
      name: reports
      mountPath: /opt/render/project/src/reports
      sizeGB: 1
